
build:
	@spm build

deploy:
	@rm -rf ../../sea-modules/angular-examples/phonecat2
	@mkdir  ../../sea-modules/angular-examples/phonecat2
	@mkdir  ../../sea-modules/angular-examples/phonecat2/1.0.0
	@cp     dist/*.* ../../sea-modules/angular-examples/phonecat2/1.0.0
	@echo
	@echo   " deploy to seajs-modules/angular-examples/phonecat2/1.0.0"
	@echo
