
build:
	@spm build

deploy:
	@rm -rf ../../sea-modules/angular-examples/phonecart
	@mkdir  ../../sea-modules/angular-examples/phonecart
	@mkdir  ../../sea-modules/angular-examples/phonecart/1.0.0
	@cp     dist/*.* ../../sea-modules/angular-examples/phonecart/1.0.0
	@echo
	@echo   " deploy to seajs-modules/angular-examples/phonecart/1.0.0"
	@echo
